Rdf to n3
cs-23-sw7-07/solid-interoperability pull request #12
Opened 2023-11-09 11:39 UTC by Darkros1245

Can now parse RDFs to AccessAuthorization, DataAuthorization, and DataRegistration objects

2023-11-09 12:18 UTC, S3JER requested changes

2023-11-09 12:18 UTC, S3JER commented on src/data-management/Utils/get-accessmode-from-str.ts
> +export function getAccessmodeFromStr(accessMode: string): AccessMode {
Behøver ikke skrive FromStr, det ligger lidt i ens property functionen skal have.

2023-11-09 12:18 UTC, S3JER commented on src/data-management/Utils/get-accessmode-from-str.ts
> +    case "http://www.w3.org/ns/auth/acl#Read": {
I stedet for at skrive hele urlen så lav en variable til det der er det samme som eventuelt hedder baseUrl som du så bruger til at sætte sammen med resten. Fx: baseUrl = "http://www.w3.org/ns/auth/"
case baseUrl + "acl#Read"

2023-11-09 12:18 UTC, S3JER commented on src/data-management/Utils/get-date-from-str.ts
> +export function getDateFromStr(date: string): Date {
Samme problem som før, behøver ikke vide at det er FromStr da det er selvgivene ud fra parmeteren

2023-11-09 12:18 UTC, S3JER commented on src/data-management/Utils/get-date-from-str.ts
> +  return new Date(date.slice(1, -44));
hvad sker der her?

2023-11-09 12:18 UTC, S3JER commented on src/data-management/Utils/get-identity-from-web-id.ts
> +export function getIdentityFromWebId(web_id: string): string {
```suggestion
export function getIdentity(web_id: string): string {
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/Utils/get-scope-of-auth-from-str.ts
> +export function getScopeOfAuthFromStr(scopeOfAuth: string): GrantScope {
```suggestion
export function getScopeOfAuth(scopeOfAuth: string): GrantScope {
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/Utils/get-date-from-str.ts
> +export function getDateFromStr(date: string): Date {
```suggestion
export function getDate(date: string): Date {
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/Utils/get-accessmode-from-str.ts
> +export function getAccessmodeFromStr(accessMode: string): AccessMode {
```suggestion
export function getAccessmode(accessMode: string): AccessMode {
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/authorization/access-auhorization.ts
> +  static makeAccessAuthorizationFromArgsMap(
```suggestion
  static makeAccessAuthorization(
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/authorization/data-authorization.ts
> +  static makeDataAuthorizationFromArgsMap(
```suggestion
  static makeDataAuthorization(
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/data-registration/data-registration.ts
> +  static makeDataRegistrationFromArgsMap(
```suggestion
  static makeDataRegistration(
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +import { fetchResource } from "../../Utils/fetch-resource";
```suggestion
import { getRDF } from "../../Utils/get-RDF-from-file";
import { ApplicationAgent, SocialAgent } from "../agent";
import { DataAuthorization } from "../authorization/data-authorization";
import { DataRegistration } from "../data-registration/data-registration";
import { getAccessmode } from "../../Utils/get-accessmode-from-str";
import { getScopeOfAuth } from "../../Utils/get-scope-of-auth-from-str";
import { getDate } from "../../Utils/get-date-from-str";
import { fetchResource } from "../../Utils/fetch-resource";
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +      const rdf: string = getRDFFromFile(docPath);
```suggestion
      const rdf: string = getRDF(docPath);
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +        case "http://www.w3.org/ns/solid/interop#grantedBy": {
Lav det eksempl som nævnt før med dele urlen op i en base og så append den del vi er intereseret i

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +          args.set("grantedAt", getDateFromStr(quad.object.id));
```suggestion
          args.set("grantedAt", getDate(quad.object.id));
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +                DataAuthorization.makeDataAuthorizationFromArgsMap(
```suggestion
                DataAuthorization.makeDataAuthorization(
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +              DataAuthorization.makeDataAuthorizationFromArgsMap(
```suggestion
              DataAuthorization.makeDataAuthorization(
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +            DataRegistration.makeDataRegistrationFromArgsMap(
```suggestion
            DataRegistration.makeDataRegistration(
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +          else args.set("accessMode", [getAccessmodeFromStr(quad.object.id)]);
```suggestion
            args.get("accessMode").push(getAccessmodequad.object.id));
          else args.set("accessMode", [getAccessmode(quad.object.id)]);
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +              .push(getAccessmodeFromStr(quad.object.id));
```suggestion
              .push(getAccessmode(quad.object.id));
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +              getAccessmodeFromStr(quad.object.id),
```suggestion
              getAccessmode(quad.object.id),
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +            getScopeOfAuthFromStr(quad.object.id),
```suggestion
            getScopeOfAuth(quad.object.id),
```

2023-11-09 12:18 UTC, S3JER commented on src/data-management/data-model/factory/rdfFactory.ts
> +          args.set("updatedAt", getDateFromStr(quad.object.id));
```suggestion
          args.set("registeredAt", getDate(quad.object.id));
          break;
        }
        case "http://www.w3.org/ns/solid/interop#inheritsFromAuthorization": {
          args.set(
            "inheritsFromAuthorization",
            DataAuthorization.makeDataAuthorization(
              await this.parse(quad.object.id),
            ),
          );
          break;
        }
        case "http://www.w3.org/ns/solid/interop#updatedAt": {
          args.set("updatedAt", getDate(quad.object.id));
```

2023-11-09 12:18 UTC, S3JER commented on test/test-convert-to-rdf-functions/create-rdf-tree.test.ts
> +import { getRDFFromFile } from '../../src/data-management/Utils/get-RDF-from-file'
```suggestion
import { getRDF } from '../../src/data-management/Utils/get-RDF-from-file'
```

2023-11-09 12:18 UTC, S3JER commented on test/test-convert-to-rdf-functions/create-rdf-tree.test.ts
> +        const expected = getRDFFromFile(join(PATH_TO_RDFS_EXAMPLES, "agents/c4562da9SocialAgentRegistration/c4562da9.ttl"))
```suggestion
        const expected = getRDF(join(PATH_TO_RDFS_EXAMPLES, "agents/c4562da9SocialAgentRegistration/c4562da9.ttl"))
```

2023-11-09 12:18 UTC, S3JER commented on test/test-convert-to-rdf-functions/create-rdf-tree.test.ts
> +        const expected = getRDFFromFile(join(PATH_TO_RDFS_EXAMPLES, "agents/2f2f3628ApplicationRegistration/2f2f3628.ttl"))
```suggestion
        const expected = getRDF(join(PATH_TO_RDFS_EXAMPLES, "agents/2f2f3628ApplicationRegistration/2f2f3628.ttl"))
```

2023-11-09 12:18 UTC, S3JER commented on test/test-convert-to-rdf-functions/create-rdf-tree.test.ts
> +    const expected = getRDFFromFile(join(PATH_TO_RDFS_EXAMPLES, arg.expect_rdf_file_path))
```suggestion
    const expected = getRDF(join(PATH_TO_RDFS_EXAMPLES, arg.expect_rdf_file_path))
```

2023-11-09 12:18 UTC, S3JER commented on test/test-convert-to-rdf-functions/create-rdf-tree.test.ts
> +    const expected = getRDFFromFile(join(PATH_TO_RDFS_EXAMPLES, arg.expect_rdf_file_path))
```suggestion
    const expected = getRDF(join(PATH_TO_RDFS_EXAMPLES, arg.expect_rdf_file_path))
```

2023-11-09 12:18 UTC, S3JER commented on test/test-convert-to-rdf-functions/create-rdf-tree.test.ts
> +    const expected = getRDFFromFile(join(PATH_TO_RDFS_EXAMPLES, arg.expect_rdf_file_path))
```suggestion
    const expected = getRDF(join(PATH_TO_RDFS_EXAMPLES, arg.expect_rdf_file_path))
```

2023-11-09 12:18 UTC, S3JER commented on test/test-convert-to-rdf-functions/create-rdf-tree.test.ts
> +    const expected = getRDFFromFile(join(PATH_TO_RDFS_EXAMPLES, arg.expect_rdf_file_path))
```suggestion
    const expected = getRDF(join(PATH_TO_RDFS_EXAMPLES, arg.expect_rdf_file_path))
```

2023-11-09 12:18 UTC, S3JER commented on test/test-convert-to-rdf-functions/create-rdf-tree.test.ts
> +    const expected = getRDFFromFile(join(PATH_TO_RDFS_EXAMPLES, arg.expect_rdf_file_path))
```suggestion
    const expected = getRDF(join(PATH_TO_RDFS_EXAMPLES, arg.expect_rdf_file_path))
```

2023-11-09 12:18 UTC, S3JER commented on test/test-convert-to-rdf-functions/parse.test.ts
> +    const accessAuthorization: AccessAuthorization = AccessAuthorization.makeAccessAuthorizationFromArgsMap(args);
```suggestion
    const accessAuthorization: AccessAuthorization = AccessAuthorization.makeAccessAuthorization(args);
```

2023-11-09 12:22 UTC, henneboy requested changes
Almost looks good to me, plz see comments

2023-11-09 12:22 UTC, henneboy commented on src/data-management/Utils/get-accessmode-from-str.ts
Add a default case for error handling, what happens if a new auth mode is added, og someone calls the function with "awdadw"?

2023-11-09 12:22 UTC, henneboy commented on src/data-management/Utils/get-date-from-str.ts
Use the index of the " char instead of magic index positions. In the function please supply an examples of the input string, is it meant to work with any string containing a date? It is a util after all ;)

2023-11-09 12:22 UTC, henneboy commented on src/data-management/Utils/get-identity-from-web-id.ts
depricated

2023-11-09 12:22 UTC, henneboy commented on src/data-management/Utils/get-scope-of-auth-from-str.ts
default case throwing an exception for error handling?

2023-11-09 12:22 UTC, henneboy commented on src/data-management/data-model/factory/rdfFactory.ts
> +        if (quad) quads.push(quad);
be consistent using brackets or not plz

2023-11-09 12:22 UTC, henneboy commented on src/data-management/data-model/factory/rdfFactory.ts
> +          //console.log(quad);
throw on default

2023-11-09 12:22 UTC, Mikkel-Boje commented on src/data-management/Utils/get-scope-of-auth-from-str.ts
> +export function getScopeOfAuthFromStr(scopeOfAuth: string): GrantScope {
Enig, input typpen siger at der er fromStr

2023-11-09 13:00 UTC, Mikkel-Boje commented on src/data-management/Utils/get-accessmode-from-str.ts
> +    case "http://www.w3.org/ns/auth/acl#Write": {
Please make a variable for the https addresses to make the case more readable

2023-11-13 08:16 UTC, S3JER requested changes

2023-11-13 08:16 UTC, S3JER commented on src/data-management/Utils/get-RDF.ts
> +export function getRDFFromPath(path: string): string {
```suggestion
export function getRDF(path: string): string {
```
Husk det gir sig selv ud fra parameteren

2023-11-13 08:18 UTC, henneboy commented on src/data-management/Utils/get-date.ts
> +  //return new Date(date.slice(1, -44));
Remove this outcommented code :)

2023-11-16 09:32 UTC, S3JER approved these changes

2023-11-16 09:36 UTC, henneboy approved these changes
Det vigtigste er at vi er sunde og raske...

2023-11-16 09:39 UTC, merged